#pragma once

#define MASTER_LEFT

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP12
#define SERIAL_USART_RX_PIN GP13

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0

#define BOOTMAGIC_ROW_RIGHT 5
#define BOOTMAGIC_COLUMN_RIGHT 6

// #define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
